const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
const SIGN_IN_FAIL = 'SIGN_IN_FAIL';

const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
const SIGN_UP_FAIL = 'SIGN_UP_FAIL';

const TOGGLE_SIGN_IN = 'TOGGLE_SIGN_IN';
const TOGGLE_SIGN_UP = 'TOGGLE_SIGN_UP';
const GET_PRODUCT = 'GET_PRODUCT';
const CHANGE_TITLE = 'CHANGE_TITLE';
const LOGGED = 'LOGGED';
const LOGOUT = 'LOGOUT';


const OPEN_CREATE_PRODUCT = 'OPEN_CREATE_PRODUCT';
const CLOSE_CREATE_PRODUCT = 'CLOSE_CREATE_PRODUCT';
const OPEN_UPDATE_PRODUCT = 'OPEN_UPDATE_PRODUCT';
const CLOSE_UPDATE_PRODUCT = 'CLOSE_UPDATE_PRODUCT';
const OPEN_DELETE_PRODUCT = 'OPEN_DELETE_PRODUCT';
const CLOSE_DELETE_PRODUCT = 'CLOSE_DELETE_PRODUCT';

const OPEN_CREATE_CATEGORY = 'OPEN_CREATE_CATEGORY';
const CLOSE_CREATE_CATEGORY = 'CLOSE_CREATE_CATEGORY';
const OPEN_UPDATE_CATEGORY = 'OPEN_UPDATE_CATEGORY';
const CLOSE_UPDATE_CATEGORY = 'CLOSE_UPDATE_CATEGORY';
const OPEN_DELETE_CATEGORY = 'OPEN_DELETE_CATEGORY';
const CLOSE_DELETE_CATEGORY = 'CLOSE_DELETE_CATEGORY';

const OPEN_CREATE_ACC = 'OPEN_CREATE_ACC';
const CLOSE_CREATE_ACC = 'CLOSE_CREATE_ACC';
const OPEN_UPDATE_ACC = 'OPEN_UPDATE_ACC';
const CLOSE_UPDATE_ACC = 'CLOSE_UPDATE_ACC';
const OPEN_DELETE_ACC = 'OPEN_DELETE_ACC';
const CLOSE_DELETE_ACC = 'CLOSE_DELETE_ACC';

const KEY_SEARCH = 'KEY_SEARCH';

const GET_MORE_TO_LOVE_REQUEST = 'GET_MORE_TO_LOVE_REQUEST';
const GET_MORE_TO_LOVE_SUCCESS = 'GET_MORE_TO_LOVE_SUCCESS';
const GET_MORE_TO_LOVE_FAIL = 'GET_MORE_TO_LOVE_FAIL';

const GET_CARTS_BY_USER_ID_REQUEST = 'GET_CARTS_BY_USER_ID_REQUEST';
const GET_CARTS_BY_USER_ID_SUCCESS = 'GET_CARTS_BY_USER_ID_SUCCESS';
const GET_CARTS_BY_USER_ID_FAIL = 'GET_CARTS_BY_USER_ID_FAIL';

const GET_RECOMMENDED_PRODUCTS_REQUEST = 'GET_RECOMMENDED_PRODUCTS_REQUEST';
const GET_RECOMMENDED_PRODUCTS_SUCCESS = 'GET_RECOMMENDED_PRODUCTS_SUCCESS';
const GET_RECOMMENDED_PRODUCTS_FAIL = 'GET_RECOMMENDED_PRODUCTS_FAIL';


const actionTypes = {
    SIGN_IN_SUCCESS,
    SIGN_IN_REQUEST,
    SIGN_IN_FAIL,

    SIGN_UP_FAIL,
    SIGN_UP_REQUEST,
    SIGN_UP_SUCCESS,

    TOGGLE_SIGN_IN,
    CHANGE_TITLE,
    TOGGLE_SIGN_UP,
    GET_PRODUCT,
    LOGGED,
    LOGOUT,
    KEY_SEARCH,

    OPEN_CREATE_PRODUCT,
    CLOSE_CREATE_PRODUCT,
    OPEN_UPDATE_PRODUCT,
    CLOSE_UPDATE_PRODUCT,
    OPEN_DELETE_PRODUCT,
    CLOSE_DELETE_PRODUCT,

    OPEN_CREATE_CATEGORY,
    CLOSE_CREATE_CATEGORY,
    OPEN_UPDATE_CATEGORY,
    CLOSE_UPDATE_CATEGORY,
    OPEN_DELETE_CATEGORY,
    CLOSE_DELETE_CATEGORY,

    OPEN_CREATE_ACC,
    CLOSE_CREATE_ACC,
    OPEN_UPDATE_ACC,
    CLOSE_UPDATE_ACC,
    OPEN_DELETE_ACC,
    CLOSE_DELETE_ACC,

    GET_CARTS_BY_USER_ID_FAIL,
    GET_CARTS_BY_USER_ID_REQUEST,
    GET_CARTS_BY_USER_ID_SUCCESS,

    GET_MORE_TO_LOVE_FAIL,
    GET_MORE_TO_LOVE_REQUEST,
    GET_MORE_TO_LOVE_SUCCESS,

    GET_RECOMMENDED_PRODUCTS_FAIL,
    GET_RECOMMENDED_PRODUCTS_REQUEST,
    GET_RECOMMENDED_PRODUCTS_SUCCESS
}

export default actionTypes;