const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
const SIGN_IN_FAIL = 'SIGN_IN_FAIL';

const TOGGLE_SIGN_IN = 'TOGGLE_SIGN_IN';
const TOGGLE_SIGN_UP = 'TOGGLE_SIGN_UP';
const GET_PRODUCT = 'GET_PRODUCT';
const CHANGE_TITLE = 'CHANGE_TITLE';
const LOGGED = 'LOGGED';
const LOGOUT = 'LOGOUT';

const GET_MORE_TO_LOVE_REQUEST = 'GET_MORE_TO_LOVE_REQUEST';
const GET_MORE_TO_LOVE_SUCCESS = 'GET_MORE_TO_LOVE_SUCCESS';
const GET_MORE_TO_LOVE_FAIL = 'GET_MORE_TO_LOVE_FAIL';

const GET_CARTS_BY_USER_ID_REQUEST = 'GET_CARTS_BY_USER_ID_REQUEST';
const GET_CARTS_BY_USER_ID_SUCCESS = 'GET_CARTS_BY_USER_ID_SUCCESS';
const GET_CARTS_BY_USER_ID_FAIL = 'GET_CARTS_BY_USER_ID_FAIL';

const GET_RECOMMENDED_PRODUCTS_REQUEST = 'GET_RECOMMENDED_PRODUCTS_REQUEST';
const GET_RECOMMENDED_PRODUCTS_SUCCESS = 'GET_RECOMMENDED_PRODUCTS_SUCCESS';
const GET_RECOMMENDED_PRODUCTS_FAIL = 'GET_RECOMMENDED_PRODUCTS_FAIL';


const actionTypes = {
    SIGN_IN_REQUEST,
    TOGGLE_SIGN_IN,
    CHANGE_TITLE,
    TOGGLE_SIGN_UP,
    GET_PRODUCT,
    LOGGED,
    LOGOUT,

    GET_CARTS_BY_USER_ID_FAIL,
    GET_CARTS_BY_USER_ID_REQUEST,
    GET_CARTS_BY_USER_ID_SUCCESS,

    GET_MORE_TO_LOVE_FAIL,
    GET_MORE_TO_LOVE_REQUEST,
    GET_MORE_TO_LOVE_SUCCESS,

    GET_RECOMMENDED_PRODUCTS_FAIL,
    GET_RECOMMENDED_PRODUCTS_REQUEST,
    GET_RECOMMENDED_PRODUCTS_SUCCESS
}

export default actionTypes;